const express = require('express');
const router = express.Router();
const mongoose = require('mongoose');
const User = require('../models/User');
const Asset = require('../models/Asset');
const SharedDocument = require('../models/SharedDocument');
const { generateReply, generateAssetSummary, generateWarrantyClaimEmail } = require('../utils/aiEngine');
// Resolves an asset for AI features (summary / warranty email) when the
// requesting user is either the owner, OR the receiver of an active share
// for that asset — so a document shared via Family Vault can still get an
// AI summary / warranty email generated by the receiver, same as the owner.
async function resolveAssetForAi(assetId, userMatch) {
  const owned = await Asset.findOne({ _id: assetId, userId: userMatch.customer_id }).lean();
  if (owned) return owned;
  const share = await SharedDocument.findOne({
    assetId: String(assetId),
    status: 'active',
    $or: [{ receiverCustomerId: userMatch.customer_id }, { ownerCustomerId: userMatch.customer_id }],
  });
  if (!share) return null;
  return Asset.findById(assetId).lean();
}
router.post('/chat', async (req, res) => {
  try {
    const { email, message } = req.body;
    if (!email || !message || typeof message !== 'string' || !message.trim()) {
      return res.status(400).json({ error: 'Email and valid message are required.' });
    }
    const userMatch = await User.findOne({ email: email.toLowerCase().trim() });
    if (!userMatch) {
      return res.status(404).json({ error: 'User account not found.' });
    }
    const assets = await Asset.find({ userId: userMatch.customer_id }).lean();
    const reply = generateReply(message.trim(), assets);
    return res.status(200).json({ success: true, reply });
  } catch (err) {
    console.error("AI Chat Error:", err);
    return res.status(500).json({ error: 'Internal server error during chat processing.' });
  }
});
router.post('/summary', async (req, res) => {
  console.log("DEBUG: Incoming request body:", JSON.stringify(req.body));
  try {
    const { email, assetId } = req.body;
    const cleanEmail = email ? email.toLowerCase().trim() : null;
    const cleanId = assetId ? assetId.trim() : null;
    if (!cleanEmail || !cleanId) {
      return res.status(400).json({ error: 'Email and assetId are required.' });
    }
    if (!mongoose.Types.ObjectId.isValid(cleanId)) {
      return res.status(400).json({ error: 'Invalid asset ID format.' });
    }
    const userMatch = await User.findOne({ email: cleanEmail });
    if (!userMatch) {
      return res.status(404).json({ error: 'User account not found.' });
    }
    const asset = await resolveAssetForAi(cleanId, userMatch);
    if (!asset) {
      return res.status(404).json({ error: 'Asset not found or access denied.' });
    }
    const summary = generateAssetSummary(asset);
    return res.status(200).json({ success: true, summary });
  } catch (err) {
    console.error("AI Summary Route Error:", err);
    return res.status(500).json({ error: 'Internal server error while generating summary.' });
  }
});
router.post('/warranty-email', async (req, res) => {
  try {
    const { email, assetId } = req.body;
    const cleanEmail = email ? email.toLowerCase().trim() : null;
    const cleanId = assetId ? assetId.trim() : null;
    if (!cleanEmail || !cleanId) {
      return res.status(400).json({ error: 'Email and assetId are required.' });
    }
    if (!mongoose.Types.ObjectId.isValid(cleanId)) {
      return res.status(400).json({ error: 'Invalid asset ID format.' });
    }
    const userMatch = await User.findOne({ email: cleanEmail });
    if (!userMatch) {
      return res.status(404).json({ error: 'User account not found.' });
    }
    const asset = await resolveAssetForAi(cleanId, userMatch);
    if (!asset) {
      return res.status(404).json({ error: 'Asset not found or access denied.' });
    }
    const { subject, body } = generateWarrantyClaimEmail(asset, userMatch);
    return res.status(200).json({ success: true, subject, body });
  } catch (err) {
    console.error("AI Warranty Email Route Error:", err);
    return res.status(500).json({ error: 'Internal server error while generating warranty claim email.' });
  }
});
module.exports = router;